version: "3.4"
services:
  bot:
    image: docker.pkg.github.com/legigor/akinator_slava_bot/akinator_slava_bot:${VERSION}
    build:
      context: .
    environment:
      - TELEBOT_TOKEN
    deploy:
      mode: replicated
      replicas: 1
