name: Build and Deploy

on: [push]

jobs:

  main:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set build version
        run: |
          echo $(date +%s) > .VERSION
      - name: Build
        run: |
          export VERSION=$(cat .VERSION)
          docker-compose build
      - name: Publish
        run: |
          export VERSION=$(cat .VERSION)
          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker-compose push
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          export VERSION=$(cat .VERSION)
          export DOCKER_HOST=ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          docker stack deploy --with-registry-auth -c docker-compose.yml akinator
        env:
          TELEBOT_TOKEN: ${{ secrets.TELEBOT_TOKEN }}
