name: Build and Deploy

on: [push]

jobs:

  all:
    runs-on: ubuntu-latest
    env:
      VERSION=$(date +%s)
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker-compose build
      - name: Publish
        run: |
          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker-compose push
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          export DEPLOY_HOST=46.101.108.91
          export DEPLOY_USER=root
          export DOCKER_HOST=ssh://$DEPLOY_USER@$DEPLOY_HOST

          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          docker stack deploy --with-registry-auth -c docker-compose.yml akinator
        env:
          TELEBOT_TOKEN: ${{ secrets.TELEBOT_TOKEN }}
