name: Build and Deploy

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker-compose build
      - name: Publish
        run: |
          docker login docker.pkg.github.com --username legigor --password ${{ secrets.GITHUB_TOKEN }}
          docker-compose push
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          ssh-keyscan -H 46.101.108.91  >> ~/.ssh/known_hosts
          docker -l=debug -H ssh://root@46.101.108.91 ps
