name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker-compose build
      - name: Publish
        run: |
          docker login docker.pkg.github.com --username legigor --password ${{ secrets.GITHUB_TOKEN }}
          docker-compose push
      - name: Deploy
        run: |
          echo Deploying here!
